stages:
  - test
  - build
  - deploy

# -- test -------------------

.test: &test
  before_script:
    - python -m pip install setuptools
  script:
    - python -m pip install .
    - make -C test

test:2.7:
  <<: *test
  image: python:2.7

test:3.4:
  <<: *test
  image: python:3.4

test:3.5:
  <<: *test
  image: python:3.5

test:3.6:
  <<: *test
  image: python:3.6

# -- build ------------------

build:tarball:
  image: python:3.6
  stage: build
  script:
    - python setup.py sdist
  artifacts:
    expire_in: 3h
    paths:
      - dist

.build:wheel:manylinux1: &wheel-manylinux1
  image: quay.io/pypa/manylinux1_x86_64
  stage: build
  before_script:
    - PYTAG=$(echo ${CI_JOB_NAME} | sed 's/.*:\(.*\)-manylinux1/\1/')
    - PYTHON="/opt/python/${PYTAG}/bin/python"
    - $PYTHON -m pip install wheel auditwheel
  script:
    - $PYTHON setup.py bdist_wheel -d wheels/
    - auditwheel repair wheels/*.whl -w dist/
    - $PYTHON -m pip install -q dist/*.whl
  artifacts:
    expire_in: 3h
    paths:
      - dist

build:wheel:cp27-cp27m-manylinux1:
  <<: *wheel-manylinux1

build:wheel:cp27-cp27mu-manylinux1:
  <<: *wheel-manylinux1

build:wheel:cp34-cp34m-manylinux1:
  <<: *wheel-manylinux1

build:wheel:cp35-cp35m-manylinux1:
  <<: *wheel-manylinux1

build:wheel:cp36-cp36m-manylinux1:
  <<: *wheel-manylinux1

build:el7:
  image: ligo/base:el7
  stage: build
  before_script:
    - mkdir -p dist/el7
    - yum install -yq rpm-build python-setuptools
  script:
    - python setup.py sdist
    - rpmbuild -tb dist/ligo-segments-*.tar.gz
    - mv ~/rpmbuild/RPMS/*/python*-ligo-segments-*.rpm dist/el7/
  artifacts:
    expire_in: 3h
    paths:
      - dist

build:debian:jessie:
  image: ligo/software:jessie
  stage: build
  before_script:
    - mkdir -p dist/jessie/
    - apt-get update -yqq
    - apt-get install -yq python-all-dev python-setuptools python3-all-dev python3-setuptools
  script:
    - dpkg-buildpackage -us -uc
    - mv ../python*-ligo-segments_*.deb dist/jessie/
  artifacts:
    expire_in: 3h
    paths:
      - dist

build:debian:stretch:
  image: ligo/software:stretch
  stage: build
  before_script:
    - mkdir -p dist/stretch/
    - apt-get update -yqq
    - apt-get install -yq python-all-dev python-setuptools python3-all-dev python3-setuptools
  script:
    - dpkg-buildpackage -us -uc
    - mv ../python*-ligo-segments_*.deb dist/stretch/
  artifacts:
    expire_in: 3h
    paths:
      - dist

# -- deploy -----------------

deploy:
  stage: deploy
  image: python
  script:
    - python -m pip install twine
    - twine upload dist/ligo-segments-*tar.gz dist/ligo_segments*.whl  # credentials provided in secret variables
  dependencies:
    - build:tarball
    - build:wheel:cp27-cp27m-manylinux1
    - build:wheel:cp27-cp27mu-manylinux1
    - build:wheel:cp34-cp34m-manylinux1
    - build:wheel:cp35-cp35m-manylinux1
    - build:wheel:cp36-cp36m-manylinux1
  only:
    - /^v\d+\.\d+\.\d+([abc]\d*)?$/  # PEP-440 compliant version (tags)
  except:
    - branches
